language: groovy
dist: trusty
sudo: true
jdk:
    - openjdk8
install:
    - sudo apt-get -qq update
    - sudo apt-get -qq -y install docker.io curl
    - curl -fsSL get.nextflow.io | bash
script:
    - bash test-with-docker.sh
