language: groovy
dist: trusty
sudo: true
notifications:
  irc:
    channels:
      - "irc.uvt.nl#gitlama"
    template:
      - "%{repository_slug}#%{build_number} %{message} --> %{build_url}"
    skip_join: true
jdk:
    - openjdk8
install:
    - sudo apt-get -qq update
    - sudo apt-get -qq -y install curl
    - curl -fsSL get.nextflow.io | bash
    - docker pull proycon/lamachine:piccl
script:
    - bash test.sh
